.\" (C) Copyright 2000, 2004
.\" International Business Machines Corporation and others.
.\" All Rights Reserved. This program and the accompanying
.\" materials are made available under the terms of the
.\" Common Public License v1.0 which accompanies this distribution.
.TH IPRCONFIG 8 "February 2005"
.SH NAME
iprconfig \- IBM Power RAID storage adapter configuration/recovery utility
.SH SYNOPSIS
.BI "iprconfig [-e editor] [-k dir] [-c command]"
.sp
.BI "iprconfig --version --debug --force"
.SH DESCRIPTION
.B iprconfig
is used to configure IBM Power RAID storage adapters, display information
about them, and to perform adapter and disk unit recovery. 
The menu options are: 
.PP
.B 1. Display hardware status.
.br
This option can be used to display various information regarding
the IBM Power RAID adapters attached to the system and the disk 
units controlled by them. For each adapter and disk unit, their 
/dev name, physical location, description, vendor/product ID, and
hardware status will be available. Beside each resource is an OPT 
field. By entering a 1 beside any resource, detailed information 
about that resource can be obtained. For an adapter resource, this 
will display the adapter firmware version and the physical location 
amongst other things.
.PP
.B 2. Work with Disk Arrays
.br
This option will present a second menu containing disk array related
commands. 
.PP
.B Display disk array status
is used to display the status of disk arrays on the system. 
.PP
.B Create a disk array
is used to create a disk array.
.PP
.B Delete a disk array
is used to delete disk arrays. Selecting this option will provide you 
with a list of disk arrays which can be deleted.
.PP
.B Add a device to a disk array
is used to include devices of similar capacity into an existing disk 
array. This function is currently only supported for RAID 5 and RAID 6 
disk arrays.
.PP
.B Format device for advanced function
is used to format disks to 522 bytes/sector so that they may be used in
a disk array.
.PP
.B Format device for JBOD function (512)
is used to format disks to 512 bytes/sector so that they may be used 
as standalone disks.
.PP
.B Create a hot spare
is used to designate a device as a dedicated hot spare.
.PP
.B Delete a hot spare
is used to unconfigure a previously configured hot spare.
.PP
.B Force RAID Consistency Check
is used to force a consistency check on a RAID array. All ipr adapters 
continually perform background consistency checking when idle. This 
option can be used to force a consistency check to be performed.
.PP
.B 3. Work with disk unit recovery
is used to perform the following disk unit recovery actions:
.PP
.B Concurrent add device
is used to concurrently add a new disk to a running system. This feature
is only supported with SES (SCSI Enclosure Services) packaging.
.PP
.B Concurrent remove device
is used to concurrently remove a disk from a running system.
This feature is only supported with SES (SCSI Enclosure Services) packaging.
.PP
.B Initialize and format disk unit
is used to issue a SCSI format command to attached devices. A format
unit command has special meaning to the adapter and is used as a service
action for certain error conditions. Formatting a disk unit will lose
all data on that drive.
.PP
.B Reclaim IOA cache storage
is used to repair cache error conditions. 
.B ATTENTION:
Use this option with care. This is used to discard data from the cache
and may result in data loss. This option is designed to be used by
authorized IBM hardware customer engineers.
.PP
.B Rebuild disk unit data
is generally used following concurrent maintenance. Select this option after
a failing array member device has been replaced to reconstruct the device as 
an active array member.
.PP
.B Work with resources containing cache battery packs
is used to display information regarding rechargeable cache battery packs 
and to force rechargeable cache battery packs into an error state so that
they can be replaced prior to failure. 
.B ATTENTION:
Once an error has been forced on a rechargeable cache battery pack write
caching will be disabled until the battery pack is replaced.
.PP
.B 4. Work with SCSI bus configuration
is used to change configurable SCSI bus attributes, such as maximum SCSI
bus speed, SCSI initiator ID, etc.
.PP
.B 5. Work with driver configuration
is used to change driver configurable attributes, such as log_level.
.PP
.B 6. Work with disk configuration
is used to change configurable disk attributes, such as queue depth.
.PP
.B 7. Download microcode
is used to download microcode to ipr adapters and attached SCSI disks.
.PP
.B 8. Analyze Log
is an option available to analyze /var/log/messages* files. By default
it will use vi as the editor to open the concatenated error log files.
This can be changed by using option 6 on the
.B Kernel Messages Log 
menu. Selecting
option 1 on the Kernel Messages Log menu will display only the most recent 
errors logged by the ipr device driver and may be useful to filter out 
some of the clutter. Option 2 will display all recorded errors logged by the
ipr device driver. Option 3 will display all kernel messages. Option 4 will
display errors logged by the iprconfig utility. This may be useful for
debugging problems. Option 5 can be used to change where the tool looks
to find the kernel messages files. The default is to look in /var/log.
.SH OPTIONS
.TP
.B \-e editor
Default editor for viewing error logs. The default editor is vi, but can be 
changed with this parameter.
.TP
.B -k directory
Kernel messages root directory. Root directory to look for kernel messages.
Default is /var/log.
.TP
.B -c command
Command line, non-interactive commands. Currently supported commands include:
.TP
.B raid-create [-r raid_level] [-s stripe_size_in_kb] [devices...]
Create a RAID array. RAID level can be any supported RAID level for the given
adapter, such as 0, 10, 5, 6. Currently supported stripe sizes in kb 
include 16, 64, and 256. If raid_level is not specified, it will default to
RAID 5. If stripe size is not specified, it will default to the recommended
stripe size for the selected RAID level. Devices are specified with their full
name, either the /dev/sd name or the /dev/sg name is acceptable. Example array
creation:
.br
.B iprconfig -c raid-create -r 5 -s 64 /dev/sda /dev/sdb /dev/sdc
.br
This would create a RAID 5 array with a 64k stripe size using the specified
devices.
.TP
.B raid-delete [RAID device]
Delete the specified RAID array. Specify either the /dev/sd name or the /dev/sg
name. Only 1 array can be deleted with a single command. Example:
.br
.B iprconfig -c raid-delete /dev/sda
.br
This would delete the disk array represented by /dev/sda
.TP
.B \-\-version
Print version number of 
.B iprconfig
.TP
.B \-\-debug
Enable additional error logging. Enabling this will result in additional 
errors logging to /var/log/messages.
.TP
.B \-\-force
Disable safety checks. Use this to disable safety checks in iprconfig. 
This will allow you to format devices that are not at the appropriate 
code levels. Only use this option if you really know what you are doing. 
.SH AUTHOR
Brian King <brking@us.ibm.com>
.SH NOTES
.TP
.B Notes on using under iSeries 5250 telnet
.PP
Only use this utility across 5250 telnet when there are no other options
available to you. Since there may be occasions when 5250 telnet is your only
option to access your iSeries Linux console, every attempt has been made to 
make this utility usable under 5250 telnet. By following a few guidelines,
you can make your 5250 telnet experience more productive and much less
frustrating.
.PP
1. First of all, it will be helpful to know how the keys are mapped under
5250 telnet. From the 5250 telnet window, hit ESC. This will get you to the 
.B Send TELNET Control Functions
menu. Take option 6 to display the keyboard map. Take note of how TAB, ESC, 
CTLC, and SENDWOCR are bound. They will be useful in the future.
.PP
2. When selecting menu options, enter the menu number, followed by the
enter key, same as usual.
.PP
3. When typing single character commands (eg. r=Refresh), type the single
character followed by the SENDWOCR key (F11 by default).
.PP
4. When on a device/array/IOA selection screen (eg. Display Disk Unit Details),
do NOT use the arrow keys to navigate. Instead use the TAB key (F7 by default)
to navigate these screens.
.PP
5. Beware of the backspace and delete keys. As a rule do NOT use them. 
.PP
6. When editing the root kernel message log directory or the default editor,
you may use the arrow keys, but not the backspace and delete keys. Use the 
space bar to remove already typed characters.
