.\" (C) Copyright 2000, 2005
.\" International Business Machines Corporation and others.
.\" All Rights Reserved. This program and the accompanying
.\" materials are made available under the terms of the
.\" Common Public License v1.0 which accompanies this distribution.
.TH IPRINIT 8 "February 2005"
.SH NAME
iprinit - IBM Power RAID adapter/device initialization utility
.SH SYNOPSIS
.B iprinit
.sp
.BI "iprinit --debug --daemon --use-polling --use-uevents"
.SH DESCRIPTION
.B iprinit
is used to setup IBM Power RAID adapters and devices for optimal 
performance. It will enable U320 scsi speeds if it is determined the 
disk enclosure supports it. It will also enable tagged command queuing.
Any scsi bus attributes, such as bus width, or disk attributes, such 
as queue depth, that have been setup by iprconfig will be loaded as well. 
It is desired that this be called in the boot process, using the init.d
script provided.
.SH OPTIONS
.TP
.B \-\-version
Print the version number of
.B iprinit
.TP
.B \-\-debug
Enable additional error logging. Enabling this will result in additional 
errors logging to /var/log/messages.
.TP
.B \-\-daemon
Run as a daemon to handle adapters and devices being hotplugged.
.TP
.B \-\-use-polling
Do not use netlink/uevent notification, but rather poll for adapter and
device configuration changes.
.TP
.B \-\-use-uevents
Use netlink/uevent notification rather than polling for adapter and
device configuration changes. If not specified, polling will be used
until the first uevent notification appears, then netlink will be used.
.SH AUTHOR
Brian King (brking@us.ibm.com)
