.\" (C) Copyright 2000, 2004
.\" International Business Machines Corporation and others.
.\" All Rights Reserved. This program and the accompanying
.\" materials are made available under the terms of the
.\" Common Public License v1.0 which accompanies this distribution.
.TH IPRUPDATE 8 "February 2005"
.SH NAME
iprupdate - IBM Power RAID adapter/device microcode update utility
.SH SYNOPSIS
.B iprupdate
.sp
.BI "iprupdate --debug --check_only --daemon --use-polling --use-uevents"
.SH DESCRIPTION
.B iprupdate
is used to update the microcode on IBM storage adapters and the disk units
attached to them to a minimum supported level. It can be run at any time 
while the ipr device driver is loaded. The utility will check the 
microcode revision level of each storage adapter/disk unit on the system and 
compare it to the microcode revision level that is installed in /etc/microcode,
/usr/lib/microcode, and /lib/firmware. 
If the microcode level on the adapter/device is below the minimum supported 
level and the level of the latest image is newer, the microcode will be updated
to the latest level available. It is desired that this be called in the boot 
process. 
.SH OPTIONS
.TP
.B \-\-version
Print the version number of
.B iprupdate
.TP
.B \-\-debug
Enable additional error logging. Enabling this will result in additional 
errors logging to /var/log/messages.
.TP
.B \-\-check_only
Check if any adapters or disk units are below their minimum supported level.
.TP
.B \-\-daemon
Run as a daemon to handle adapters and devices being hotplugged.
.TP
.B \-\-use-polling
Do not use netlink/uevent notification, but rather poll for adapter and
device configuration changes.
.TP
.B \-\-use-uevents
Use netlink/uevent notification rather than polling for adapter and
device configuration changes. If not specified, polling will be used
until the first uevent notification appears, then netlink will be used.
.SH AUTHOR
Brian King (brking@us.ibm.com)
