.TH IPRUPDATE 8 "February 2004"
.SH NAME
iprupdate - IBM Power RAID adapter/device microcode update utility
.SH SYNOPIPR
.B iprupdate
.SH DESCRIPTION
.B iprupdate
is used to update the microcode on IBM storage adapters and the disk units
attached to them to a minimum supported level. It can be run at any time 
while the ipr device driver is loaded. The utility will check the 
microcode revision level of each storage adapter/disk unit on the system and 
compare it to the microcode revision level that is installed in /etc/microcode. 
If the microcode level on the adapter/device is below the minimum supported 
level and the level of the image is newer, the microcode will be updated. 
It is desired that this be called in the boot process.  
.SH OPTIONS
.TP
.B \-\-version
Print the version number of
.B iprupdate
.SH AUTHOR
Brian King (brking@us.ibm.com)
