#!/bin/sh
# Copyright (C) 2004 IBM Corporation
#
# Author: Brian King <brking@us.ibm.com>
#
# iprdump
#
# System startup script for the ipr dump facility
#
### BEGIN INIT INFO
# Provides: iprdump
# Required-Start:    $local_fs $syslog $iprinit
# Should-Start:      $remote_fs
# Required-Stop:     $local_fs $syslog $remote_fs $iprinit
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the ipr dump daemon
# Description:       Start the ipr dump daemon
### END INIT INFO

IPRDUMP=/sbin/iprdump
test -x $IPRDUMP || exit 5
. /lib/lsb/init-functions

start() {
    echo -n "Starting ipr dump daemon"
    start_daemon $IPRDUMP

    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
	log_success_msg " "
    else
	log_failure_msg " "
    fi
}

stop() {
    echo -n "Shutting down ipr dump daemon"
    killproc $IPRDUMP

    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
	log_success_msg " "
    else
	log_failure_msg " "
    fi
}

restart() {
    $0 stop
    $0 start
}

reload() {
    echo -n "Reload ipr dump daemon"
    $0 stop  &&  $0 start
}

status() {
    echo -n "Checking for iprdump daemon: "

    pidofproc $IPRDUMP

    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
	log_success_msg " "
    else
	log_failure_msg " "
    fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    reload)
	reload
	;;
    status)
	status
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload}"
	exit 1
	;;
esac
