#!/bin/bash
#
#       /etc/rc.d/init.d/iprinitd
#
# Runs the iprinit utility for the ipr device driver
#
# chkconfig:  2345 20 90
# description: Starts the iprinit daemon which is used to setup \
#   ipr adapters and devices for optimal performance and reliability.
# processname: iprinit

prog="iprinit"
RETVAL=0

. /etc/init.d/functions

start() {
        echo -n $"Starting $prog: "
        daemon $prog --daemonize
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/iprinit
        echo
        return $RETVAL
}

stop() {
       echo -n $"Stopping $prog: "
       killproc $prog
       RETVAL=$?
       [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/iprinit
       echo
       return $RETVAL
}

rhstatus() {
       status $prog
}

restart() {
       stop
       start
}

reload() {
       echo -n $"Reloading $prog: "
       killproc $prog -HUP
       RETVAL=$?
       echo
       return $RETVAL
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  reload)
        reload
        ;;
  status)
        rhstatus
        ;;
  condrestart)
        [ -f /var/lock/subsys/iprinit ] && restart || :
        ;;
  *)
        echo "Usage: $0 {start|stop|status|restart|condrestart}"
        exit 1
esac

exit $?
