#!/bin/sh
# Copyright (C) 2004 IBM Corporation
#
# Author: Brian King <brking@us.ibm.com>
#
# iprinit
#
# System startup script for the ipr init facility
#
### BEGIN INIT INFO
# Provides: iprinit
# Required-Start:    $local_fs $syslog
# Should-Start:      $remote_fs
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the ipr init daemon
# Description:       Start the ipr initialization daemon
### END INIT INFO

IPRINIT=/sbin/iprinit
test -x $IPRINIT || exit 5
. /lib/lsb/init-functions

start() {
    echo -n "Starting ipr initialization daemon"
    start_daemon $IPRINIT --daemon

    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
	log_success_msg " "
    else
	log_failure_msg " "
    fi
}

stop() {
    echo -n "Shutting down ipr initialization daemon"
    killproc $IPRINIT
    
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
	log_success_msg " "
    else
	log_failure_msg " "
    fi
}

restart() {
    $0 stop
    $0 start
}

reload() {
    echo -n "Reload ipr initialization daemon"
    $0 stop  &&  $0 start
}

status() {
    echo -n "Checking for ipr initialization daemon: "

    pidofproc $IPRINIT

    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
	log_success_msg " "
    else
	log_failure_msg " "
    fi
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    reload)
	reload
	;;
    status)
	status
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload}"
	exit 1
	;;
esac
