#! /bin/sh
# Copyright (C) 2004 IBM Corporation
#
# Author: Brian King <brking@us.ibm.com> 2004
#
# iprupdate
#
# System startup script for the ipr microcode update facility
#
### BEGIN INIT INFO
# Provides: iprupdate
# Required-Start:    $local_fs $syslog
# Should-Start:      $remote_fs
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the iprupdate utility
# Description:       Start the iprupdate utility
### END INIT INFO

IPRUPDATE=/sbin/iprupdate
test -x $IPRUPDATE || exit 5
. /lib/lsb/init-functions

start() {
	echo "Checking ipr microcode levels"
	$IPRUPDATE

	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
	    echo -n "Completed ipr microcode updates"
	    log_success_msg " "
	else
	    echo -n "Completed ipr microcode updates"
	    log_failure_msg " "
	fi
}

stop() {
    exit 3
}

restart() {
    exit 3
}

reload() {
    exit 3
}

status() {
    exit 3
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	reload)
		reload
	;;
	status)
		status
	;;
	*)
		echo "Usage: $0 {start|stop|status|restart|reload}"
		exit 1
	;;
esac
